### ISSUE TITLE
upgrade to iroh v0.14

### ISSUE THREAD

**Issue by divagant-martian** [n0-computer/iroh-examples#39]
- [x] content-discovery `v0.13.0` -> `v0.14.0` #38 
- [x] doc-photos
  - [x] `0v.10.0` -> `v0.11.0` #38 
  - [x] ~`0v.11.0` -> `v0.12.0` @b5 offered to move this up to 0.14~ ended up being removed in #46 
  - [x] ~`0v.12.0` -> `v0.13.0`~
  - [x] ~`0v.13.0` -> `v0.14.0`~
- [x] dumbpipe-web
  - [x] requires first a release of `dumbpipe`
  - [x] `0v.12.0` -> `v0.13.0` #44
  - [x] `0v.13.0` -> `v0.14.0`
- [x] extism `0v.13.0` -> `v0.14.0` #38 
- [x] iroh-automerge `0v.13.0` -> `v0.14.0` #38 
- [x] iroh-gateway
  - [x] `0v.12.0` -> `v0.13.0` #38 
  - [x] `0v.13.0` -> `v0.14.0` #38 
- [x] ~iroh-ipfs~ #42 
- [x] iroh-pkarr-naming-system
  - [x] `0v.12.0` -> `v0.13.0` #38 
  - [x] `0v.13.0` -> `v0.14.0` #38 
- [x] iroh-pkarr-node-discovery `0v.13.0` -> `v0.14.0` #38 
- [x] iroh-s3-bao-store `0v.13.0` -> `v0.14.0` #45

**Comment by ramfox** [comment]
dumbpipe v0.6.0 has been released!
